/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Track = IDL.Record({
  'id' : IDL.Text,
  'pan' : IDL.Float64,
  'muted' : IDL.Bool,
  'soloed' : IDL.Bool,
  'order' : IDL.Nat,
  'name' : IDL.Text,
  'color' : IDL.Text,
  'volume' : IDL.Float64,
  'projectId' : IDL.Text,
  'effectsChain' : IDL.Text,
});
export const Project = IDL.Record({
  'id' : IDL.Text,
  'bpm' : IDL.Nat,
  'timeSignatureDenominator' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
  'timeSignatureNumerator' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addTrack' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Track], []),
  'createProject' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
      [Project],
      [],
    ),
  'deleteProject' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteTrack' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getProject' : IDL.Func([IDL.Text], [IDL.Opt(Project)], ['query']),
  'getTracksForProject' : IDL.Func([IDL.Text], [IDL.Vec(Track)], ['query']),
  'listProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'updateProject' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
      [Project],
      [],
    ),
  'updateTrack' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Bool,
        IDL.Bool,
        IDL.Text,
        IDL.Nat,
      ],
      [Track],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Track = IDL.Record({
    'id' : IDL.Text,
    'pan' : IDL.Float64,
    'muted' : IDL.Bool,
    'soloed' : IDL.Bool,
    'order' : IDL.Nat,
    'name' : IDL.Text,
    'color' : IDL.Text,
    'volume' : IDL.Float64,
    'projectId' : IDL.Text,
    'effectsChain' : IDL.Text,
  });
  const Project = IDL.Record({
    'id' : IDL.Text,
    'bpm' : IDL.Nat,
    'timeSignatureDenominator' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
    'timeSignatureNumerator' : IDL.Nat,
  });
  
  return IDL.Service({
    'addTrack' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Track], []),
    'createProject' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
        [Project],
        [],
      ),
    'deleteProject' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteTrack' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getProject' : IDL.Func([IDL.Text], [IDL.Opt(Project)], ['query']),
    'getTracksForProject' : IDL.Func([IDL.Text], [IDL.Vec(Track)], ['query']),
    'listProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'updateProject' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
        [Project],
        [],
      ),
    'updateTrack' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Bool,
          IDL.Bool,
          IDL.Text,
          IDL.Nat,
        ],
        [Track],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };