/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Project {
  'id' : string,
  'bpm' : bigint,
  'timeSignatureDenominator' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'updatedAt' : bigint,
  'timeSignatureNumerator' : bigint,
}
export interface Track {
  'id' : string,
  'pan' : number,
  'muted' : boolean,
  'soloed' : boolean,
  'order' : bigint,
  'name' : string,
  'color' : string,
  'volume' : number,
  'projectId' : string,
  'effectsChain' : string,
}
export interface _SERVICE {
  'addTrack' : ActorMethod<[string, string, string], Track>,
  'createProject' : ActorMethod<[string, bigint, bigint, bigint], Project>,
  'deleteProject' : ActorMethod<[string], boolean>,
  'deleteTrack' : ActorMethod<[string], boolean>,
  'getProject' : ActorMethod<[string], [] | [Project]>,
  'getTracksForProject' : ActorMethod<[string], Array<Track>>,
  'listProjects' : ActorMethod<[], Array<Project>>,
  'updateProject' : ActorMethod<
    [string, string, bigint, bigint, bigint],
    Project
  >,
  'updateTrack' : ActorMethod<
    [string, string, string, number, number, boolean, boolean, string, bigint],
    Track
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];